package ingsw.codex_naturalis.model.observerObservable;

public enum Event {

    SETUP_STATUS,
    GAMEPLAY_STATUS,
    HAND_CHANGED,
    PLAYER_AREA_CHANGED,
    DECK_CHANGED,
    REVEALED_RESOURCE_CARDS_CHANGED,
    REVEALED_GOLD_CARDS_CHANGED,
    TURN_STATUS_CHANGED,
    TURN_CHANGED,
    MESSAGE_SENT

}
