package ingsw.codex_naturalis.model.observerObservable;

public enum Event {

    SETUP_1,
    GAME_STATUS_CHANGED,
    HAND_CHANGED,
    PLAYER_AREA_CHANGED,
    DECK_CHANGED,
    REVEALED_RESOURCE_CARDS_CHANGED,
    REVEALED_GOLD_CARDS_CHANGED,
    TURN_STATUS_CHANGED,
    TURN_CHANGED,
    PLAYER,
    COLOR_SETUP, INITIAL_CARD_PLAYED, HANDS_SETUP, MESSAGE_SENT

}
